package com.sml.stp.navigation

object AppScreens {
    const val MAIN_SCREEN = "MAIN_SCREEN"
    const val CHOOSE_SPEEDTEST_SCREEN = "CHOOSE_SPEEDTEST_SCREEN"
    const val SPEEDTEST_RETROFIT_SCREEN = "SPEEDTEST_RETROFIT_SCREEN"
    const val SPEEDTEST_JSPEEDTEST_SCREEN = "SPEEDTEST_JSPEEDTEST_SCREEN"
}